ecommerce:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: WCAYPEB-PL20954
      user: SIYOLISESOLANI
      password: Siyolise19970911
      role: ACCOUNTADMIN
      database: ecommerce_db
      warehouse: COMPUTE_WH
      schema: analytics
      threads: 1
      client_sessions_keep_alive: False